employee_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('employee_logs.urls')),
    path(r'users', include('users.urls'))
]

employee_logs/urls.py
from django.urls import path

from . import views

app_name = 'employee_logs'
urlpatterns = [
    path(r'', views.index, name='index'),

    path(r'main_tasks', views.main_tasks, name='main_tasks'),

    # path(r'end_date/(?P<task_id>\d+)/$', views.end_date, name="end_date"),

    path(r'sub_task/(?P<task_id>\d+)/$', views.sub_task, name='sub_task'),

    path(r'new_main_task', views.new_main_task, name='new_main_task'),

    # path(r'new_sub_task/(?P<task_id>\d+)\$', views.new_sub_task, name='new_sub_task'),

    path(r'edit_sub_task/(?P<entry_id>\d+)/$', views.edit_sub_task, name='edit_sub_task'),
]

users/urls.py
"""defines URL patterns for users"""

from django.urls import path
from django.contrib.auth.views import login
from . import views

app_name = 'users'
urlpatterns = [
    # login page
    path('login/', login, {'template_name': 'users/login.html'}, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

employee_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    """a task an employee will perform"""
    text = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

employee_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Task, Entry
from .ModelsForm import TaskForm, EntryForm


def index(request):
    """the homepage"""
    return render(request, 'employee_logs/index.html')


@login_required
def main_tasks(request):
    main_tasks = Task.objects.filter(owner=request.user).order_by('date')
    context = {'main_tasks': main_tasks}
    return render(request, 'employee_logs/main_tasks.html', context)


@login_required
def sub_task(request, task_id):
    sub_task = Task.objects.get(id=task_id)
    # Make sure the task belong to the current user
    if sub_task.owner != request.user:
        print(" sorry this is not what a wrong page")

    entries = sub_task.entry_set.order_by('-date')
    context = {'sub_task': sub_task, 'entries': entries}
    return render(request, 'employee_logs/sub_task.html', context)


@login_required
def new_main_task(request):
    """this function add a new task"""
    if request.method == "POST":
        # POST data submitted; process data
        form = TaskForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('employee_logs:main_tasks'))
    else:
        # No data submitted; create a blank form.
        form = TaskForm()

    context = {'form': form}
    return render(request, 'employee_logs/new_main_task.html', context)


@login_required
def edit_sub_task(request, entry_id):
    """Editing a sub ta sk"""
    entry = Entry.objects.get(id=entry_id)
    task = entry.task
    if task.owner != request.user:
        raise Http404

    if request.method == 'POST':
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('employee_logs:sub_task', args=[task.id]))
    else:
        form = EntryForm(instance=entry)

    context = {'entry': entry, 'task': task, 'form': form}
    return render(request, 'employee_logs/edit_sub_task.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import  login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('employee_logs:index'))


def register(request):
    """Register a new employee"""
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('employee_logs:index'))
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'users/register.html', context)

employee_logs/templates/employee_logs/base.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->

<!--<head>-->
<!--    <meta charset="utf-8">-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1">-->
<!--    <title>Fasyl Log</title>-->
<!---->
<!---->
<!--</head>-->

<!--<body>-->
<!--  &lt;!&ndash; Static navbar &ndash;&gt;-->
<!--  <nav class="navbar navbar-default navbar-static-top">-->
<!--    <div class="container">-->

<!--      <div class="navbar-header">-->
<!--        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">-->
<!--        </button>-->
<!--        <a class="navbar-brand" href="{% url 'employee_logs:index' %}"> Your Logs</a>-->
<!--      </div>-->

<!--      <div id="navbar" class="navbar-collapse collapse">-->
<!--              <ul class="nav navbar-nav navbar-right">-->
<!--              {% if user.is_authenticated %}-->
<!--              <li><a href="{% url 'employee_logs:main_tasks' %}">Task</a></li>-->
<!--              <li><a>Hello, {{ user.username }}.</a></li>-->
<!--              <li><a href="{% url 'users:logout' %}">log out</a></li>-->
<!--              {% else %}-->
<!--              <li><a href="{% url 'users:register' %}">register</a></li>-->
<!--              <li><a href="{% url 'users:login' %}">log in</a></li>-->
<!--              {% endif %}-->
<!--          </ul>-->
<!--      </div>&lt;!&ndash;/.nav-collapse &ndash;&gt;-->

<!--    </div>-->
<!--  </nav>-->
<!--</body>-->


<p>
    <h1> <a href="{% url 'employee_logs:index' %}">Your Log</a></h1>

    {% if user.is_authenticated %}
      <a href="{% url 'employee_logs:main_tasks' %}"> Tasks </a> <br>
     <h2> Hello, {{ user.username }}</h2>
      <a href="{% url 'users:logout' %}"> log out</a>
    {% else %}
      <a href="{% url 'users:register' %}">register</a>
      <a href="{% url 'users:login' %}"> log in </a>
    {%endif%}
</p>

{% block content %}

{% endblock content %}

employee_logs/templates/employee_logs/edit_sub_task.html
{% extends "employee_logs/base.html" %}

{% block content %}
    <p>
        <a href="{% url 'employee_logs:sub_task' task.id %}">{{topic }}</a>
    </p>

    <p>Edit Activity</p>
    <form action="{% url 'employee_logs:edit_sub_task' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>

    </form>

{% endblock content %}

employee_logs/templates/employee_logs/index.html
{% extends "employee_logs/base.html" %}


{% block content %}
   <h3>Welcome to Task Log.</h3>

{% if user.is_authenticated %}
  <h3>click on Task in the menu to get started</h3>
{% else %}
  <h3>Log In or<a href="{% url 'users:register' %}"> <i> Register an Account </i> </a>
    to make your own log</h3>
{%endif%}

{% endblock content %}

employee_logs/templates/employee_logs/main_tasks.html
{% extends "employee_logs/base.html" %}

{% block content %}

<p> Tasks Name </p>
    <ul type="none">
        {% for task in main_tasks %}
          <li>
              <a href="{% url 'employee_logs:sub_task' task.id %}">{{ task }}  </a>
              <p> Start Date {{ task.date|date:'M d, Y H:i' }}</p>
              <hr>
          </li>
        {% empty %}
          <li>No tasks have been added yet. </li>
        {% endfor %}
    </ul>
<a href="{% url 'employee_logs:new_main_task' %}">add a new task </a>
{% endblock content %}

employee_logs/templates/employee_logs/new_main_task.html
{% extends "employee_logs/base.html" %}


{% block content %}
    <p>Add new Task: </p>
    <form action="{%url 'employee_logs:new_main_task'%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">add </button>

    </form>
{% endblock content  %}

employee_logs/templates/employee_logs/sub_task.html
{% extends "employee_logs/base.html" %}

{% block content %}
    <p>Topic: {{ task }}</p>

    <p>Entries: </p>
    <a>add a new entry</a>


    <ul>
        {% for entry in entries %}
          <li>
              <p>{{ entry.date|date:'M d, Y H:i' }}</p>
              <p>{{ entry.text|linebreaks }}</p>
              <a href="{% url 'employee_logs:edit_sub_task' entry.id %}">Edit</a>
          </li>
        {% empty %}
          <li>
              there are no entries for this topic yet.
          </li>
        {% endfor %}
    </ul>

{% endblock content %}

users/templates/users/login.html
{% extends "employee_logs/base.html" %}


{% block content %}
    {% if form.errors %}
    <p> Your User Name or pass word did not match. Please try again. </p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token  %}
        {{ form.as_p }}

        <button name="submit"> login </button>
        <input type="hidden" name="next" value="{% url 'employee_logs:index' %}">
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "employee_logs/base.html" %}


{% block content %}

    <form method="post" action="{% url 'users:register' %}">
       {% csrf_token %}
       {{ form.as_p }}

        <button name="submit">register</button>
        <input type="hidden" name="next" value="{% url 'employee_logs:index' %}" />
    </form>

{% endblock content %}